USE [GD1C2025] 
GO

------------------------------ ELIMINAR PROCEDIMIENTOS -----------------------------

IF OBJECT_ID('CALLE_DE_LUNA.migrar_medidas', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_medidas
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_tipo_material', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_tipo_material
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_material', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_material
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_modelos', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_modelos
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_sillones', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_sillones
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Tela', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Tela
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Madera', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Madera
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Relleno', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Relleno
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Sucursal', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Sucursal
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_provincia', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_provincia
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_localidad', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_localidad
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Direccion', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Direccion
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Cliente', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Cliente
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Factura', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Factura
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Detalle_Factura', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Detalle_Factura
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Pedido', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Pedido
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Detalle_Pedido', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Detalle_Pedido
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Cancelacion', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Cancelacion
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Envio', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Envio
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Proveedor', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Proveedor
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Compra', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Compra
GO

IF OBJECT_ID('CALLE_DE_LUNA.migrar_Item_Compra', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.migrar_Item_Compra
GO

IF OBJECT_ID('CALLE_DE_LUNA.Migrar_medidas', 'P') IS NOT NULL
    DROP PROCEDURE CALLE_DE_LUNA.Migrar_medidas
GO

------------------------------ ELIMINAR TABLAS ----------------------------- 

IF OBJECT_ID('CALLE_DE_LUNA.Envio', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Envio
GO

IF OBJECT_ID('CALLE_DE_LUNA.Detalle_Factura', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Detalle_Factura
GO

IF OBJECT_ID('CALLE_DE_LUNA.Factura', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Factura
GO

IF OBJECT_ID('CALLE_DE_LUNA.Cancelacion', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Cancelacion
GO

IF OBJECT_ID('CALLE_DE_LUNA.Detalle_Pedido', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Detalle_Pedido
GO

IF OBJECT_ID('CALLE_DE_LUNA.Pedido', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Pedido
GO

IF OBJECT_ID('CALLE_DE_LUNA.Item_Compra', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Item_Compra
GO

IF OBJECT_ID('CALLE_DE_LUNA.Compra', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Compra
GO

IF OBJECT_ID('CALLE_DE_LUNA.Tela', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Tela
GO

IF OBJECT_ID('CALLE_DE_LUNA.Madera', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Madera
GO

IF OBJECT_ID('CALLE_DE_LUNA.Relleno', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Relleno
GO

IF OBJECT_ID('CALLE_DE_LUNA.Material', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Material
GO

IF OBJECT_ID('CALLE_DE_LUNA.Tipo_Material', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Tipo_Material
GO

IF OBJECT_ID('CALLE_DE_LUNA.Sillon', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Sillon
GO

IF OBJECT_ID('CALLE_DE_LUNA.Modelo', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Modelo
GO

IF OBJECT_ID('CALLE_DE_LUNA.Medida', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Medida
GO

IF OBJECT_ID('CALLE_DE_LUNA.Sucursal', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Sucursal
GO

IF OBJECT_ID('CALLE_DE_LUNA.Proveedor', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Proveedor
GO

IF OBJECT_ID('CALLE_DE_LUNA.Cliente', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Cliente
GO

IF OBJECT_ID('CALLE_DE_LUNA.Direccion', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Direccion
GO

IF OBJECT_ID('CALLE_DE_LUNA.Localidad', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Localidad
GO

IF OBJECT_ID('CALLE_DE_LUNA.Provincia', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.Provincia
GO

------------------------------ ELIMINAR TABLAS MODELO BI -----------------------------

IF OBJECT_ID('CALLE_DE_LUNA.BI_Tiempo', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Tiempo
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Ubicacion', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Ubicacion
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Rango_Etario', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Rango_Etario
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Turno_Ventas', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Turno_Ventas
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Tipo_Material', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Tipo_Material
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Modelo_Sillon', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Modelo_Sillon
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Estado_Pedido', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Estado_Pedido
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Sucursal', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Sucursal
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Cliente', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Cliente
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Compras', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Compras
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Ventas', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Ventas
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Pedidos', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Pedidos
GO

IF OBJECT_ID('CALLE_DE_LUNA.BI_Envios', 'U') IS NOT NULL
    DROP TABLE CALLE_DE_LUNA.BI_Envios
GO

------------------------------ ELIMINAR ESQUEMA ----------------------------- 
/*
IF EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CALLE_DE_LUNA')
    DROP SCHEMA CALLE_DE_LUNA
GO
*/